apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: esnd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: esnd
    app.kubernetes.io/part-of: byoc-app-vtbd
  name: esnd
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: esnd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: esnd
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-sais-tenant/byoc-app-vtbd/esnd@sha256:74fa539b13709b1866c491d56ff25c0823ebb200963c271bad7276365df850a0
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
