apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: esnd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: esnd
    app.kubernetes.io/part-of: byoc-app-vtbd
  name: esnd
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: esnd
status:
  loadBalancer: {}
